Default: &defaults
  user: splittest
  password: splittest
  host: localhost
  port: 5432
  database: splittest
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod-split-testing_test
  <<: *defaults

Staging:
  database: yesod-split-testing_staging
  poolsize: 100
  <<: *defaults

Production:
  database: yesod-split-testing_production
  poolsize: 100
  <<: *defaults
